//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDETicaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adresler
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string AdresIsmi { get; set; }
        public string Isim { get; set; }
        public string CepTelefonu { get; set; }
        public string Il { get; set; }
        public string Ilce { get; set; }
        public string Adres { get; set; }
        public string TC { get; set; }
        public string FaturaTuru { get; set; }
        public string FirmaAdi { get; set; }
        public string VergiDairesi { get; set; }
        public string VergiNumarasi { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
