//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDETicaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductView
    {
        public int ID { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<System.DateTime> CDate { get; set; }
        public string Tarayici { get; set; }
        public string Isim { get; set; }
        public string Versiyon { get; set; }
        public string IsletimSistemi { get; set; }
        public string IP { get; set; }
        public string Aciklama1 { get; set; }
        public string Aciklama2 { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
