//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDETicaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bankalar
    {
        public int ID { get; set; }
        public string Sirket { get; set; }
        public string Banka { get; set; }
        public string VergiNumarasi { get; set; }
        public string TerminalID { get; set; }
        public string MarchantID { get; set; }
        public string TerminalUserID { get; set; }
        public string BankName { get; set; }
        public string ClientID { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string ProvisionPassword { get; set; }
        public string PosUrl { get; set; }
        public string okURL { get; set; }
        public string failURL { get; set; }
        public string receiveURL { get; set; }
        public Nullable<bool> Aktif { get; set; }
    }
}
