//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDETicaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullanicilarXml
    {
        public int ID { get; set; }
        public string Isim { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
    }
}
