//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDETicaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.OrdersDetail = new HashSet<OrdersDetail>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime DateCreation { get; set; }
        public int CustomerId { get; set; }
        public int VendorId { get; set; }
        public int OrderStatusId { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public Nullable<bool> Aktarildi { get; set; }
        public Nullable<System.DateTime> CDate { get; set; }
        public string Isim { get; set; }
        public string CepTelefonu { get; set; }
        public string Il { get; set; }
        public string Ilce { get; set; }
        public string Adres { get; set; }
        public string TC { get; set; }
        public string FaturaTuru { get; set; }
        public string FirmaAdi { get; set; }
        public string VergiDairesi { get; set; }
        public string VergiNumarasi { get; set; }
        public string OrderID { get; set; }
        public Nullable<bool> Ertele { get; set; }
        public Nullable<bool> Aktif { get; set; }
        public string Email { get; set; }
        public string Kargo { get; set; }
        public string KargoNo { get; set; }
        public string Aciklama1 { get; set; }
        public string Aciklama2 { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual Vendor Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersDetail> OrdersDetail { get; set; }
    }
}
