//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf StronglyTypedResourceBuilder tarafından otomatik olarak oluşturuldu
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // /str seçeneği ile veya Visual Studio projesini yeniden kur.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Home", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Bu türü kesin olarak belirtilmiş kaynak sınıfını kullanarak geçerli iş parçacığının CurrentUICulture 
        ///   özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add to benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Add_to {
            get {
                return ResourceManager.GetString("Add_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Best Seller Products benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Best_Seller_Products {
            get {
                return ResourceManager.GetString("Best_Seller_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Latest Products benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Latest_Products {
            get {
                return ResourceManager.GetString("Latest_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mosted View Products benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Mosted_View_Products {
            get {
                return ResourceManager.GetString("Mosted_View_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sold By benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Sold_By {
            get {
                return ResourceManager.GetString("Sold_By", resourceCulture);
            }
        }
    }
}
