//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf StronglyTypedResourceBuilder tarafından otomatik olarak oluşturuldu
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // /str seçeneği ile veya Visual Studio projesini yeniden kur.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Cart {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Cart() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Cart", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Bu türü kesin olarak belirtilmiş kaynak sınıfını kullanarak geçerli iş parçacığının CurrentUICulture 
        ///   özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Continue Shopping benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Continue_Shopping {
            get {
                return ResourceManager.GetString("Continue_Shopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Id benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Item benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Option benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Option {
            get {
                return ResourceManager.GetString("Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SHOPPING CART benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Photo benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please Login Before Checkout benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Please_login_before_checkout {
            get {
                return ResourceManager.GetString("Please_login_before_checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Price benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quantity benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send Your Orders to Vendors benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Send_Your_Orders_to_Vendors {
            get {
                return ResourceManager.GetString("Send_Your_Orders_to_Vendors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total Price benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Total_Price {
            get {
                return ResourceManager.GetString("Total_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vendor Name benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Vendor_Name {
            get {
                return ResourceManager.GetString("Vendor_Name", resourceCulture);
            }
        }
    }
}
