//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf StronglyTypedResourceBuilder tarafından otomatik olarak oluşturuldu
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // /str seçeneği ile veya Visual Studio projesini yeniden kur.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Customer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Customer() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Customer", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Bu türü kesin olarak belirtilmiş kaynak sınıfını kullanarak geçerli iş parçacığının CurrentUICulture 
        ///   özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ACCOUNT benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ACCOUNT {
            get {
                return ResourceManager.GetString("ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adres benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t delete Trial Package benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Can_not_delete_Trial_Package {
            get {
                return ResourceManager.GetString("Can_not_delete_Trial_Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Customer Information benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Customer_Information {
            get {
                return ResourceManager.GetString("Customer_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Customer Panel benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Customer_Panel {
            get {
                return ResourceManager.GetString("Customer_Panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Customer Register benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Customer_Register {
            get {
                return ResourceManager.GetString("Customer_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E-Mail benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tam İsim benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Full_Name {
            get {
                return ResourceManager.GetString("Full_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı kilitli.  Lütfen müşteri temsilcisiyle iletişime geçiniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Invalid_Account {
            get {
                return ResourceManager.GetString("Invalid_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Giriş benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Çıkı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ORDER HISTORY benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ORDER_HISTORY {
            get {
                return ResourceManager.GetString("ORDER_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parola benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   6 ile 20 karakter olmalı ve bir sembol içermeli @, #, $, % benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Password_validate_message {
            get {
                return ResourceManager.GetString("Password_validate_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Telefon benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profil benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kaydol benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kaydol benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update Success benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Update_Success {
            get {
                return ResourceManager.GetString("Update_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı Adı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı mevcut benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Username_exists {
            get {
                return ResourceManager.GetString("Username_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hesabım benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string YOUR_ACCOUNT {
            get {
                return ResourceManager.GetString("YOUR_ACCOUNT", resourceCulture);
            }
        }
    }
}
