//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf StronglyTypedResourceBuilder tarafından otomatik olarak oluşturuldu
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // /str seçeneği ile veya Visual Studio projesini yeniden kur.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserTemplate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserTemplate() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.UserTemplate", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Bu türü kesin olarak belirtilmiş kaynak sınıfını kullanarak geçerli iş parçacığının CurrentUICulture 
        ///   özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ABOUT US benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ABOUT_US {
            get {
                return ResourceManager.GetString("ABOUT_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copyright © 2017 OctopusCodes. All rights reserved. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FAQ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Go benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Home benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   INFORMATION benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string INFORMATION {
            get {
                return ResourceManager.GetString("INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Itemes in your cart benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Itemes_in_your_cart {
            get {
                return ResourceManager.GetString("Itemes_in_your_cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LEGAL NOTICE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string LEGAL_NOTICE {
            get {
                return ResourceManager.GetString("LEGAL_NOTICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ORDER HISTORY benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ORDER_HISTORY {
            get {
                return ResourceManager.GetString("ORDER_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SOCIAL MEDIA benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SOCIAL_MEDIA {
            get {
                return ResourceManager.GetString("SOCIAL_MEDIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sorry, an error occurred while processing your request. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Sorry {
            get {
                return ResourceManager.GetString("Sorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TERMS AND CONDITIONS benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TERMS_AND_CONDITIONS {
            get {
                return ResourceManager.GetString("TERMS_AND_CONDITIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Welcome benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
