//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf StronglyTypedResourceBuilder tarafından otomatik olarak oluşturuldu
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // /str seçeneği ile veya Visual Studio projesini yeniden kur.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Product {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Product() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Product", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Bu türü kesin olarak belirtilmiş kaynak sınıfını kullanarak geçerli iş parçacığının CurrentUICulture 
        ///   özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add to cart benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Add_to_cart {
            get {
                return ResourceManager.GetString("Add_to_cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Category benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   products are available benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string products_are_available {
            get {
                return ResourceManager.GetString("products_are_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Products List benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Products_List {
            get {
                return ResourceManager.GetString("Products_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Product Details benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Product_Details {
            get {
                return ResourceManager.GetString("Product_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Product does not exist benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Product_does_not_exist {
            get {
                return ResourceManager.GetString("Product_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Product Info benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Product_Info {
            get {
                return ResourceManager.GetString("Product_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Qty. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Related Products benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Related_Products {
            get {
                return ResourceManager.GetString("Related_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search Result benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Search_Result {
            get {
                return ResourceManager.GetString("Search_Result", resourceCulture);
            }
        }
    }
}
