//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf StronglyTypedResourceBuilder tarafından otomatik olarak oluşturuldu
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // /str seçeneği ile veya Visual Studio projesini yeniden kur.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Vendor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Vendor() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Vendor", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Bu türü kesin olarak belirtilmiş kaynak sınıfını kullanarak geçerli iş parçacığının CurrentUICulture 
        ///   özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Address benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Categories Vendor benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Categories_Vendor {
            get {
                return ResourceManager.GetString("Categories_Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Content benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Email benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Give Review benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Give_Review {
            get {
                return ResourceManager.GetString("Give_Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Give your review for vendor benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Give_your_review_for_vendor {
            get {
                return ResourceManager.GetString("Give_your_review_for_vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid Password benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Invalid_Password {
            get {
                return ResourceManager.GetString("Invalid_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Latest Vendors benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Latest_Vendors {
            get {
                return ResourceManager.GetString("Latest_Vendors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logo benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logout benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MemberShip benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MemberShip {
            get {
                return ResourceManager.GetString("MemberShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your messages sent to vendor. Thanks you very much benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string messages_sent_success {
            get {
                return ResourceManager.GetString("messages_sent_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Order for Vendor benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string New_Order_for_Vendor {
            get {
                return ResourceManager.GetString("New_Order_for_Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password have 6 to 20 characters string with at least one digit, one upper case letter, one lower case letter and one special symbol @, #, $, % benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Password_validate_message {
            get {
                return ResourceManager.GetString("Password_validate_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Payment Success benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Payment_Success {
            get {
                return ResourceManager.GetString("Payment_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Phone benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Photo Invalid benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Photo_Invalid {
            get {
                return ResourceManager.GetString("Photo_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   products are available benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string products_are_available {
            get {
                return ResourceManager.GetString("products_are_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Products of Vendor benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Products_of_Vendor {
            get {
                return ResourceManager.GetString("Products_of_Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profile benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Register benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reviews benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Reviews {
            get {
                return ResourceManager.GetString("Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send Messages to benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Send_Messages_to {
            get {
                return ResourceManager.GetString("Send_Messages_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send Messages to Vendor benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Send_Messages_to_Vendor {
            get {
                return ResourceManager.GetString("Send_Messages_to_Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Username benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Username already exists benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Username_already_exists {
            get {
                return ResourceManager.GetString("Username_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vendor does not exist benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Vendor_does_not_exist {
            get {
                return ResourceManager.GetString("Vendor_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vendor Info benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Vendor_Info {
            get {
                return ResourceManager.GetString("Vendor_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vendor Information benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Vendor_Information {
            get {
                return ResourceManager.GetString("Vendor_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vendor Panel benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Vendor_Panel {
            get {
                return ResourceManager.GetString("Vendor_Panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vendor Register benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Vendor_Register {
            get {
                return ResourceManager.GetString("Vendor_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your review sent to vendor. Thanks you very much benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Your_review_sent_to_vendor {
            get {
                return ResourceManager.GetString("Your_review_sent_to_vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You must be customer before give review benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string You_must_be_customer {
            get {
                return ResourceManager.GetString("You_must_be_customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You need login before send message benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string You_need_login {
            get {
                return ResourceManager.GetString("You_need_login", resourceCulture);
            }
        }
    }
}
